config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :people, only: [:index, :create] do
    get :details
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :person

  validates :title, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  validates :phone, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/models/person.rb
class Person < ApplicationRecord
  has_one :detail

  accepts_nested_attributes_for :detail
  validates_associated :detail

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  skip_before_action :verify_authenticity_token 

  def index
    @people = Person.all

    respond_to do |format|
      format.js { render json: @people, include: :detail }
      format.html
    end
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      render json: { person: @person, detail: @person.detail }, status: :created
    else
      render json: { errors: @person.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def details
    @person = Person.find_by(id: params[:person_id])
  end

  private

  def person_params
    params.require(:person).permit(:name, detail_attributes: [:title, :age, :phone, :email])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketcicleTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/details.turbo_stream.erb
<turbo-stream action="update" target="person_details">
  <template>
    <turbo-frame id="quote_123">
      <div style="text-align: center;">
        <h4>Title:- <%= @person.detail.title %></h4>
        <h4>Age:- <%= @person.detail.age %></h4>
        <h4>Phone:- <%= @person.detail.phone %></h4>
        <h4>Email:- <%= @person.detail.email %></h4>
      </div>
    </turbo-frame>
  </template>
</turbo-stream>

app/views/people/index.html.erb
<div class="container">
  <div class="row", style="display: flex">
    <div class="col-4 w-25" style="border-right: 1px solid black; width: 250px; height: 500px; text-align: center">
      <h1>People</h1>
      <% @people.each do |person| %>
        <%= link_to "#{person.name}", person_details_path(person.id), data: { turbo_stream: true } %>
        <br/>
      <% end %>
    </div>
    <div class="col-8", style="width: 50%">
      <h1 style="text-align: center">Details</h1>
      <div id='person_details'></div>
    </div>
  </div>
</div>